export const contact = {
  heading: "Let’s talk about\nyour next chapter.",
  intro: "A new opportunity. A growing business. A story ready to be told properly. Tell us what you’re working towards.",
  consultation: "Start with a free 15-minute consultation.",
  labels: { name: "Full name", email: "Email", phone: "WhatsApp number", service: "Service needed", budget: "Budget range", description: "Project description", deadline: "Preferred deadline", consent: "I agree that Mahlangu Online Solutions may use these details to respond to my enquiry." },
  budgets: ["Please advise", "Under R500", "R500–R1,500", "R1,500–R5,000", "R5,000+"],
  placeholders: { service: "Choose a service", description: "Tell us about your goals, what you need and anything we should know." },
  composer: {
    title: "Send a message",
    eyebrow: "WhatsApp or email",
    channelLegend: "Send with",
    labels: { name: "Your name", email: "Your email", phone: "WhatsApp number", service: "What can we help with?", message: "Your message" },
    placeholder: "Tell us what you need, and anything we should know — deadlines, the role you’re applying for, or how your business works today.",
    whatsappNote: "Opens WhatsApp with your message ready to send.",
    emailNote: "Goes straight to Musa’s inbox. Replies go to the email address you enter.",
    privacy: "Please don’t include ID numbers, passwords or banking details.",
    whatsappSubmit: "Continue in WhatsApp", emailSubmit: "Send email", sending: "Sending…",
    openedTitle: "WhatsApp is ready.", openedBody: "Your message is waiting in WhatsApp. Press send there to deliver it.", openAgain: "Open WhatsApp again",
    sentTitle: "Message sent.", sentBody: "Thank you. Musa will reply to", another: "Write another message",
    fallback: "The website couldn’t send your email just now. Your message is still here — send it from your email app or on WhatsApp instead.",
    mailApp: "Open in my email app", whatsappInstead: "Send on WhatsApp",
    launcher: "Message us", dialogEyebrow: "Direct line", dialogTitle: "Send Musa a message", close: "Close message window",
  },
  send: "Send enquiry", sending: "Sending your enquiry…", success: "Your enquiry is on its way.", successBody: "Thank you for sharing your plans. We’ll respond using the contact details you provided.", error: "Your enquiry could not be delivered. Please try again or send it directly on WhatsApp.", unavailable: "Online enquiries are not connected yet. Please send your enquiry on WhatsApp or email us directly.", privacy: "Please don’t include identity numbers, passwords or sensitive documents in this form.", optional: "Optional", choose: "Please choose", another: "Send another enquiry", whatsappDraft: "Send these details on WhatsApp", formTitle: "Tell us what you have in mind", received: "Enquiry received",
};
