export const categories = ["All work", "Brand Identity", "Graphic Design", "Business Documents"] as const;
export type Project = { slug: string; name: string; discipline: string; categories: (typeof categories)[number][]; image: string; alt: string; colour: string; intro: string; challenge: string; strategy: string; design: string; deliverables: string[]; outcome: string; note?: string };
export const projects: Project[] = [
  { slug: "atchar", name: "Atchar — South African Classic", discipline: "Food brand & packaging identity", categories: ["Brand Identity", "Graphic Design"], image: "/images/atchar.webp", alt: "Atchar identity board with warm red and gold palette, logo, packaging and branded applications", colour: "ochre", intro: "A food brand with a distinctly South African character.", challenge: "Present a food product line through a connected packaging brand system.", strategy: "Bring the product, visual identity and applications into a consistent family, as shown in the original portfolio board.", design: "Warm reds, golds and cream sit alongside a circular emblem and strong product naming.", deliverables: ["Packaging brand system", "Logo and colour applications", "Product presentation board"], outcome: "A documented identity and packaging system shown in the studio portfolio. Commercial results have not been supplied." },
  { slug: "kori-driving-school", name: "Kori Driving School", discipline: "Brand identity & promotional design", categories: ["Brand Identity", "Graphic Design"], image: "/images/kori.webp", alt: "Kori Driving School brand board with blue identity, driving imagery and promotional flyer", colour: "blue", intro: "A clear, recognisable identity for a driving school.", challenge: "Bring the school’s identity, promotional messaging and package information together.", strategy: "Organise the promotion around the school name, driving context and clear service information.", design: "Blue, white and high-contrast typography connect the identity to its promotional applications.", deliverables: ["Brand identity", "Promotional flyer", "Package and pricing presentation"], outcome: "Identity and promotional work are documented in the source portfolio. No performance figures are claimed.", note: "Website case study pending confirmation and supplied website imagery." },
  { slug: "faith-and-exhaustion", name: "The Space Between Faith & Exhaustion", discipline: "Author brand & book cover system", categories: ["Brand Identity", "Graphic Design"], image: "/images/author.webp", alt: "The Space Between Faith and Exhaustion author identity, book cover and publishing applications", colour: "sand", intro: "An expressive visual world for an author and their book.", challenge: "Create a connected author identity and cover system around the book’s title and themes.", strategy: "Link the cover, typography, palette and supporting materials in one coherent presentation.", design: "Earth-toned colours and expressive editorial typography establish the visual language shown in the portfolio.", deliverables: ["Author brand system", "Book cover system", "Supporting brand applications"], outcome: "The author brand and cover system appear in the supplied portfolio. Publication and sales results are not claimed." },
  { slug: "mahlangu-identity", name: "Mahlangu Online Solutions", discipline: "The studio’s brand identity system", categories: ["Brand Identity", "Business Documents"], image: "/images/studio.webp", alt: "Mahlangu Online Solutions portfolio cover with the studio’s positioning", colour: "forest", intro: "Strategic thinking starts at home.", challenge: "Build an independent studio identity that brings career expertise and visual design together.", strategy: "Anchor the identity in a single idea: turning career stories into professional first impressions.", design: "Clear typography and a restrained monogram form the studio’s visual foundation.", deliverables: ["Colour palette", "Typography pairing", "Logo system", "Iconography and brand applications"], outcome: "A cohesive identity applied across web, print and client-facing documents, as recorded in the portfolio." },
];
export const portfolioCopy = { heading: "Proof of thought.\nProof of work.", intro: "A selection of identities, documents and design systems. Explore the thinking behind the finished work.", empty: "Work in this category is being prepared for publication. Tell us what you have in mind and we can discuss relevant examples.", gallery: "From the project", back: "All projects", caseLabels: ["Challenge", "Strategy", "Design", "Deliverables", "Outcome"] };

