export type Service = { id: string; title: string; shortTitle: string; description: string; outcome: string; group: "Career Services" | "Brand & Design Services" | "Digital Services"; deliverables: string[]; core?: boolean };
export const services: Service[] = [
  { id: "cv-writing", title: "Professional Resume & CV Writing", shortTitle: "CV & resume writing", group: "Career Services", core: true, description: "Achievement-focused career documents built around your experience, your industry and the opportunities you’re working towards.", outcome: "A clearer, more relevant professional story.", deliverables: ["Career and existing-document review", "Role-focused content and structure", "Readable, ATS-conscious formatting", "Final documents and usage guidance"] },
  { id: "cover-letters", title: "Cover Letters & Application Support", shortTitle: "Cover letters & applications", group: "Career Services", core: true, description: "The conversation you don’t get to have out loud. Connect your experience to what the employer actually needs to hear.", outcome: "A stronger, more confident first impression.", deliverables: ["Review of your target opportunity", "Tailored application narrative", "Clear alignment with role requirements"] },
  { id: "brand-identity", title: "Personal Brand & Logo Design", shortTitle: "Brand & logo design", group: "Brand & Design Services", core: true, description: "Cohesive visual identities — logo, colour, typography and applications — for people and businesses ready to look established.", outcome: "A consistent, memorable professional identity.", deliverables: ["Brand direction", "Logo and visual identity", "Colour and typography guidance", "Agreed brand applications"] },
  { id: "digital-presence", title: "Digital Portfolio & LinkedIn Optimisation", shortTitle: "Portfolios & LinkedIn", group: "Digital Services", core: true, description: "A purposeful online presence that makes your work easy to find, understand and remember.", outcome: "A focused presence for recruiters and decision-makers.", deliverables: ["Online-presence review", "Profile positioning and content", "Selected-work presentation", "Practical handover guidance"] },
  { id: "career-strategy", title: "Career Consulting & Document Strategy", shortTitle: "Career & document strategy", group: "Career Services", core: true, description: "One-on-one mapping of your goals into a coherent professional narrative. The strategic layer beneath every document.", outcome: "Clarity and confidence for your next move.", deliverables: ["Discovery conversation", "Career-story mapping", "Document priorities", "Actionable next steps"] },
  { id: "website-design", title: "Website Design & Development", shortTitle: "Website design & development", group: "Digital Services", description: "Clear, responsive websites that introduce your business and help visitors take the next step.", outcome: "A credible home for your business online.", deliverables: ["Agreed page structure", "Responsive design and development", "Launch and handover plan"] },
  { id: "web-portfolio", title: "Web Portfolio Development", shortTitle: "Web portfolio development", group: "Digital Services", description: "A personal site that gives your projects, experience and professional direction room to speak.", outcome: "Your work, presented with purpose.", deliverables: ["Portfolio structure", "Project presentation", "Responsive website"] },
  { id: "github", title: "GitHub Profile Setup", shortTitle: "GitHub profile setup", group: "Digital Services", description: "A clear developer profile and organised project presentation.", outcome: "Technical work that is easier to explore.", deliverables: ["Profile README", "Project organisation guidance", "Repository presentation"] },
  { id: "linkedin", title: "LinkedIn Optimisation", shortTitle: "LinkedIn optimisation", group: "Digital Services", description: "A focused headline, about section and experience narrative that reflect your direction.", outcome: "A coherent professional profile.", deliverables: ["Headline and about copy", "Experience positioning", "Profile recommendations"] },
  { id: "graphic-design", title: "Graphic Design", shortTitle: "Graphic design", group: "Brand & Design Services", description: "Purposeful visual communication for your brand’s everyday needs.", outcome: "Clear, consistent brand communication.", deliverables: ["Design direction", "Agreed artwork", "Export files"] },
  { id: "flyers", title: "Flyers & Promotional Graphics", shortTitle: "Flyers & promotional graphics", group: "Brand & Design Services", description: "Promotional materials that put the message first and make the next step clear.", outcome: "Your offer, easy to understand.", deliverables: ["Message hierarchy", "Promotional design", "Agreed print or digital exports"] },
  { id: "company-profiles", title: "Company Profiles", shortTitle: "Company profiles", group: "Brand & Design Services", description: "Introduce your business, services and capabilities in one considered document.", outcome: "A professional introduction to your business.", deliverables: ["Content organisation", "Profile layout", "Final PDF"] },
  { id: "menus", title: "Menus", shortTitle: "Menus", group: "Brand & Design Services", description: "Readable, brand-conscious menus for food and hospitality businesses.", outcome: "An offer that is easy to browse.", deliverables: ["Menu hierarchy", "Branded layout", "Agreed export formats"] },
  { id: "business-documents", title: "Business Documents", shortTitle: "Business documents", group: "Brand & Design Services", description: "Consistent business communication, from everyday documents to client-facing presentations.", outcome: "A more cohesive professional presence.", deliverables: ["Document structure", "Consistent branded formatting", "Agreed final files"] },
];
export const coreServices = services.filter(s => s.core);
export const serviceGroups = ["Career Services", "Brand & Design Services", "Digital Services"] as const;
